CREATE TABLE seats (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    available BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP
);

ALTER TABLE seats ADD COLUMN type VARCHAR(45) NOT NULL DEFAULT 'REGULAR';
ALTER TABLE seats ADD COLUMN row integer NOT NULL;
ALTER TABLE seats ADD COLUMN col integer NOT NULL;
ALTER TABLE seats ADD COLUMN location_id BIGINT NOT NULL REFERENCES locations(id) DEFAULT 1;